print("What is your name?")
name = str(input())
print("How old are you?")
age = int(input())
print("Where are you from?")
place = str(input())
print("This is ", name)
print("He(She) is ", age, "years old")
print("He(She) live in", place)
